<div class="container">
    <form class="row" action="/cadastrar" method="POST">
        <div class="form-group col-sm-6 col-md-4">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome" required="required" placeholder="Nome...">
        </div>
        <div class="form-group  col-sm-6 col-md-4">
            <label for="rg">RG</label>
            <input type="text" class="form-control" id="rg" name="rg" required="required" placeholder="00.000.000-0">
        </div>
        <div class="form-group  col-sm-6 col-md-4">
            <label for="cpf">CPF</label>
            <input type="text" class="form-control" id="cpf" name="cpf" required="required" placeholder="000.000.000-03">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="data_nascimento">Data de Nascimento</label>
            <input type="text" class="form-control" id="data_nascimento" name="data_nascimento" required="required" placeholder="00/00/0000 ">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="nome">Cargo</label>
            <div class="input-group mb-3">
                <select class="form-control" id="cargo" name="cargo">
                    <option value="">Selecionar Cargo...</option>
                    <?php
                    foreach ($this->view->cargos as $cargo) {
                        echo "<option value='" . $cargo['id'] . "'>" . $cargo['nome'] . "</option>";
                    }
                    ?>
                </select>

                <div class="input-group-append">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#cadastroCargo">
                        +
                    </button>
                </div>
            </div>





        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="salario_bruto">Sálario Bruto</label>
            <input type="text" class="form-control" id="salario_bruto" name="salario_bruto" required="required" placeholder="0000,00">
        </div>
        <div class="col-12">
            <hr />
        </div>

        <div class="form-group col-sm-6 col-md-4">
            <label for="cep">CEP</label>
            <input type="text" class="form-control" id="cep" name="cep" required="required" placeholder="00000-000">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="logradouro">Logradouro</label>
            <input type="text" class="form-control" id="logradouro" name="logradouro" required="required" placeholder="Endereço...">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="numero">Número</label>
            <input type="text" class="form-control" id="numero" name="numero" required="required" placeholder="00">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="bairro">Bairro</label>
            <input type="text" class="form-control" id="bairro" name="bairro" required="required" placeholder="Bairro...">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="cidade">Cidade</label>
            <input type="text" class="form-control" id="cidade" name="cidade" required="required" placeholder="Cidade...">
        </div>
        <div class="form-group col-sm-6 col-md-4">
            <label for="estado">Estado</label>
            <input type="text" class="form-control" id="estado" name="estado" required="required" placeholder="UF...">
        </div>
        <div class="col-md-6 offset-md-3 col-sm-12 text-center">
            <button class="btn btn-primary btn-block text-uppercase">Cadastrar colaborador</button>
        </div>


    </form>

    <div class="modal fade" id="cadastroCargo" tabindex="-1" role="dialog" aria-labelledby="cadastroCargo" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Cadastrar Cargo</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="nomeCargo">Cargo</label>
                                <input type="text" class="form-control" name="nomeCargo" id="nomeCargo">
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" id="cancelar">Cancelar</button>
                    <button type="button" class="btn btn-primary" id="btnCargo">Cadastrar</button>
                </div>
            </div>

        </div>
    </div>
</div>

<script>
    document.getElementById('btnCargo').addEventListener('click', function() {

        var xhr = new XMLHttpRequest();
        nomeCargo = document.getElementById('nomeCargo').value;
        cancelar = document.getElementById('cancelar');
        xhr.open("POST", "/cargo");
        xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");

        xhr.addEventListener("load", function() {
            if (xhr.status == 200) {
                cargo = document.getElementById('cargo');
                opt = document.createElement("option");
                elem = JSON.parse(xhr.responseText);

                opt.value = elem.id;
                opt.text = elem.nome;
                // console.log(opt);
                cargo.appendChild(opt);
                cancelar.click();

            } else {
                alert('Erro ao cadastrar Cargo');
            }


        });
        xhr.send("nome=" + nomeCargo);
    });
</script>